/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.8.1. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module accum
    ( // Inputs
      input wire  CLK // clock
    , input wire  RST // reset
    , input wire  EN // enable
    , input wire [7:0] DIN

      // Outputs
    , output wire [7:0] DOUT
    );
  reg [7:0] s = 8'd0;

  // register begin
  always @(posedge CLK or  posedge  RST) begin : s_register
    if ( RST) begin
      s <= 8'd0;
    end else if (EN) begin
      s <= (s + DIN);
    end
  end
  // register end

  assign DOUT = s;


endmodule

